SELECT distinct 
t_transaction_history_scheduler.transaction_amount,
t_transaction_history_scheduler.dst_account_type,
t_transaction_history_scheduler.dst_bank_code,
t_transaction_history_scheduler.payee_code,
t_transaction_history_scheduler.dst_bank_name,
master_biller_product.current_allowed 
FROM t_transaction_history_scheduler
left join master_biller_product
on t_transaction_history_scheduler.payee_code =master_biller_product.payee_code 
where t_transaction_history_scheduler.payee_code is not NULL
